### ISSUE TITLE
Can't download models!

### ISSUE THREAD

**Issue by frenzybiscuit** [huggingface/xet-core#373]
I am trying to download this model and it's just erroring out:

https://huggingface.co/ArtusDev/nbeerbower_EVA-abliterated-TIES-Qwen2.5-72B-AWQ

Prior to xet becoming a thing I had no issues downloading models. I have a 1Gbps connection.

Lots of errors related to "failed to lookup address information: temporary failure in name resolution" among others.

And the few threads that are downloading are incredibly slow.

**Comment by jsulz** [comment]
Hi @frenzybiscuit could you tell me a bit more about your setup? Specifically: 
* What version of `hf-xet` is installed? (a full output of `pip freeze` would be very helpful)
* What platform/operating system are you using when you encounter this? (e.g., Ubuntu, Windows, etc.)
* What API are you using to download the model? (e.g., `transformer`'s `.from_pretrained()`, `huggingface_hub`'s `snapshot_download` or `huggingface-cli download`, etc)
* Do you have any `HF_XET` environment variables set (can run `env | grep HF_XET` to see)

If you're using a version of `hf-xet` < 1.1.3, could you attempt to update to the latest version (`pip install -U hf-xet`) and try again?

**Comment by frenzybiscuit** [comment]
Here is an example.

I am using:

huggingface-cli download --local-dir . ArtusDev/nbeerbower_EVA-abliterated-TIES-Qwen2.5-72B-AWQ

The package installed:

hf_xet-1.1.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

My platform is Debian 12 64bit.

env | grep HF_XET is not set.

**Comment by jsulz** [comment]
Thanks @frenzybiscuit, appreciate it. Could you also provide a full error log statement that you're seeing so that we can troubleshoot?

**Comment by frenzybiscuit** [comment]
> Thanks [@frenzybiscuit](https://github.com/frenzybiscuit), appreciate it. Could you also provide a full error log statement that you're seeing so that we can troubleshoot?

![Image](https://github.com/user-attachments/assets/41a978d7-2e72-4d81-9c30-73d4530437cf)

**Comment by frenzybiscuit** [comment]
![Image](https://github.com/user-attachments/assets/835bf74b-3aa2-4a20-b16b-f2efc525b800)

**Comment by marked23** [comment]
I ran frenzybiscuit's command using my self-compiled hf-xet with the one-liner PR #376.  That worked for me.
![Image](https://github.com/user-attachments/assets/5cb13b6f-46cb-4985-9730-fc8cad4127a5)

Without that certificate fix in place, I get a different error than frenzybiscuit.  Not sure if this is helpful, but I wanted to share the info.
<code> Xet Storage is enabled for this repo. Downloading file from Xet Storage..
                                                                                                                                              Downloading 'model-00006-of-00009.safetensors' to '.cache/huggingface/download/KJ8cCBR2J7aBLF_InTWDtQJlP5U=.50fcca20f06e337334f6d065a9f1ebc3830d34763c921f704b9c09dbc3cb3f6b.incomplete'
Xet Storage is enabled for this repo. Downloading file from Xet Storage..
{"timestamp":"2025-06-08T02:41:09.052316Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, url: \"https://cas-server.xethub.hf.co/reconstruction/e6669b0ba54c1b9c0a3326700996dd5953c28230ebf68917e129d53fcfcd1ea3\", source: hyper_util::client::legacy::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: \"SSL routines\", function: \"tls_post_process_server_certificate\", reason: \"certificate verify failed\", file: \"ssl/statem/statem_clnt.c\", line: 2092 }]))) }, X509VerifyResult { code: 20, error: \"unable to get local issuer certificate\" })) }). Retrying..."},"filename":"/home/runner/work/xet-core/xet-core/cas_client/src/http_client.rs","line_number":175} </code>

**Comment by jsulz** [comment]
Thanks @frenzybiscuit, just wanted to let you know that we're looking into this. Thanks for the report.

**Comment by jsulz** [comment]
@frenzybiscuit thanks again - we implemented a few fixes that should help resolve the error. Could you `pip install hf_xet==1.1.4-rc1` and see if this helps?

**Comment by nynj** [comment]
Tried `pip install --force-reinstall -v "hf_xet==1.1.4-rc2"` , no change in DNS errors.  Clearing os x DNS cache after this also did not help.

`{"timestamp":"2025-06-11T21:13:26.215684Z","level":"WARN","fields":{"message":"Retry attempt #1. Sleeping 2.023317408s before the next attempt"},"filename":"/Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs","line_number":171}
{"timestamp":"2025-06-11T21:13:26.216125Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, url: \"https://transfer.xethub.hf.co/xorbs/default/d164a480026d5d7388d1f87d562b8c218df293e8539e997e958f6e7f6970dc98?X-Xet-Signed-Range=bytes%3D0-67022617&Expires=1749680004&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly90cmFuc2Zlci54ZXRodWIuaGYuY28veG9yYnMvZGVmYXVsdC9kMTY0YTQ4MDAyNmQ1ZDczODhkMWY4N2Q1NjJiOGMyMThkZjI5M2U4NTM5ZTk5N2U5NThmNmU3ZjY5NzBkYzk4P1gtWGV0LVNpZ25lZC1SYW5nZT1ieXRlcyUzRDAtNjcwMjI2MTciLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3NDk2ODAwMDR9fX1dfQ__&Signature=Hq9QSeWrTjDBYRL67uHyVL7PP6yULWPheCnCEcCtJ-kLPfHl7z9twesvZ~QYWkiKdcagkiIbagjb8-CzFj5J8TQVHPnk5QBr9DmoLNDP0Lq5ZsPo9ajTRkWFuvfpIMdlKrxFKz-ez9C8xf3BUIC~D83Y2bywx~b2uld188IO7st4D36lswhEwvLcQkomwUQPziR3bu9lKMftG2UzktB2C9qqMlsXK29kEXMH9FRTKe7MgNL-qDfa8RKHiJ3cja9wT3iPPntbpzcpzhD6Eox3cJnchuBE8TG3wqxGIPe-up9LuaAmKm6x1t08tp3NnFPWTPTbDnkLV8wdeWYe2YQaVQ__&Key-Pair-Id=K2L8F4GPSG1IFC\", source: hyper_util::client::legacy::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: nodename nor servname provided, or not known\" })) }). Retrying..."},"filename":"/Users/runner/work/xet-core/xet-core/cas_client/src/http_client.rs","line_number":200}
`

**Comment by vekiar** [comment]
Try removing xet (`pip uninstall hf_xet`). Under `mlx_lm.chat --model <model_name>` that cleared all of the dns related errors. Same for `huggingface-cli download <repo_id/model_name>`. Both seem to fail back onto http download:

> Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

**Comment by hoytak** [comment]
Thanks for the report @nynj; that one took a while to track down, but I think I finally fixed it.  Could you see if installing the newest wheel with `pip install hf_xet==v1.1.4-rc5` fixes the issue for you?

**Comment by ivegner** [comment]
I'm having a similar (related?) issue:
```
tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 350/350 [00:00<00:00, 19.5kB/s]
vocab.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 3.54MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 3.14MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 69.3kB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 612/612 [00:00<00:00, 45.9kB/s]
model.safetensors:   0%|                                                                                                                                                    | 0.00/90.9M [00:00<?, ?B/s]{"timestamp":"2025-06-13T20:11:21.136529Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, url: \"https://cas-server.xethub.hf.co/reconstruction/789fdf16a3e59f4fbfb6002967ecee539a198dadb5be74ca549aa7dc9b1b55fb\", source: hyper_util::client::legacy::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: No address associated with hostname\" })) }). Retrying..."},"filename":"/home/conda/feedstock_root/build_artifacts/hf-xet_1749033316051/work/cas_client/src/http_client.rs","line_number":200}
{"timestamp":"2025-06-13T20:11:21.139914Z","level":"WARN","fields":{"message":"Retry attempt #0. Sleeping 595.723299ms before the next attempt"},"filename":"/home/conda/feedstock_root/build_artifacts/hf-xet_1749033316051/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs","line_number":171}
{"timestamp":"2025-06-13T20:11:21.737745Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, url: \"https://cas-server.xethub.hf.co/reconstruction/789fdf16a3e59f4fbfb6002967ecee539a198dadb5be74ca549aa7dc9b1b55fb\", source: hyper_util::client::legacy::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: No address associated with hostname\" })) }). Retrying..."},"filename":"/home/conda/feedstock_root/build_artifacts/hf-xet_1749033316051/work/cas_client/src/http_client.rs","line_number":200}
{"timestamp":"2025-06-13T20:11:21.737855Z","level":"WARN","fields":{"message":"Retry attempt #1. Sleeping 5.675099331s before the next attempt"},"filename":"/home/conda/feedstock_root/build_artifacts/hf-xet_1749033316051/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reqwest-retry-0.7.0/src/middleware.rs","line_number":171}
...ad infinitum
```

`pip install hf_xet==v1.1.4-rc5` does not fix the issue. 

Downloading via CLI gives:
```
$ huggingface-cli download sentence-transformers/all-MiniLM-L6-v2
Fetching 30 files:   0%|                                                                                                                                                         | 0/30 [00:00<?, ?it/s]Downloading 'onnx/model_O1.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/1391c6fc20b5530250bc15cbe1f47578ffeca55ab0551d335cc668b6299a88ec.incomplete'
Downloading 'onnx/model_O4.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/1667d7f3ba669048b13a96ee3a44456d5e42c8f44588ae8b603430e16160c485.incomplete'
Downloading 'model.safetensors' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/53aa51172d142c89d9012cce15ae4d6cc0ca6895895114379cacb4fab128d9db.incomplete'
Downloading 'onnx/model.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/6fd5d72fe4589f189f8ebc006442dbb529bb7ce38f8082112682524616046452.incomplete'
Downloading 'onnx/model_qint8_avx512.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.incomplete'
Downloading 'onnx/model_O2.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/1de3905029190b398c7d300b530e320cf4b5e7d3dfb9af1429ebd73fd9a16faf.incomplete'
                                                                                                                                                                                                       Downloading 'onnx/model_O3.onnx' to '/home/me/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/blobs/a44f671e364dddbac31f203f07b91be6b0a35e51936e5ebfab65b6d9538b83ff.incomplete'/model_O4.onnx:   0%|                                                                                                                                                   | 0.00/45.2M [00:00<?, ?B/s]
model.safetensors:   0%|                                                                                                                                                    | 0.00/90.9M [00:00<?, ?B/sStill waiting to acquire lock on /home/me/.cache/huggingface/hub/.locks/models--sentence-transformers--all-MiniLM-L6-v2/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.lock (elapsed: 10.0 seconds):   0%|                                                                                                                                                   | 0.00/90.3M [00:00<?, ?B/s]
Still waiting to acquire lock on /home/me/.cache/huggingface/hub/.locks/models--sentence-transformers--all-MiniLM-L6-v2/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.lock (elapsed: 20.0 seconds)
Still waiting to acquire lock on /home/me/.cache/huggingface/hub/.locks/models--sentence-transformers--all-MiniLM-L6-v2/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.lock (elapsed: 30.1 seconds)
Still waiting to acquire lock on /home/me/.cache/huggingface/hub/.locks/models--sentence-transformers--all-MiniLM-L6-v2/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.lock (elapsed: 40.1 seconds)
Still waiting to acquire lock on /home/me/.cache/huggingface/hub/.locks/models--sentence-transformers--all-MiniLM-L6-v2/4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474.lock (elapsed: 50.1 seconds)
...
```

**Comment by nynj** [comment]
No improvement with rc5

**Comment by jsulz** [comment]
Hi @ivegner I believe that is a separate (although potentially related) issue; would you mind opening up a new issue so that we can investigate there?

@frenzybiscuit and @nynj we believe the most recent release will address the issue you encountered. Could you test again after updating to the most current version of `hf-xet` (`pip install -U hf-xet`) and close out the issue if it does?

If it doesn't, could you provide the number of open file descriptors your operating system allows for a single process? Running `ulimit -n` should provide the proper output.

**Comment by nynj** [comment]
New release seems to fix the issue for me.

**Comment by jsulz** [comment]
@nynj thanks for confirming. 

@frenzybiscuit I'm going to close this ticket as it seems that the new release is resolving this issue, but please reopen and comment if you're having problems. Thank you for reporting the issue!

**Comment by djholt** [comment]
Hello! I'm seeing a similar error only when xet is enabled. I currently have hf-xet 1.1.5 installed.

`ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known"`

I'm curious if this has remained an outstanding issue in any capacity, or if I should be looking at firewall restrictions or rate limits on my network.

Thanks!

Edit: The issue turned out to be the file descriptor limit. Increasing via `ulimit -Sn 4096` in the same shell resolved my issue.

**Comment by jsulz** [comment]
@djholt you might be seeing a recurrence of this issue. I just opened a new issue to track this, see https://github.com/huggingface/xet-core/issues/436

Could you provide additional details on that issue, including the:
1. Repository where you are encountering this
2. Minimum steps/script to reproduce the error
3. Output you get when running following (most interested in `hf-xet` version, OS/platform, what environment variables you have set - this should grab them all): 

```python
import os
from huggingface_hub import dump_environment_info

dump_environment_info()
```
